### ISSUE TITLE
New icon/button

### ISSUE THREAD

**Issue by moneypenny** [moneypenny/soma-chrome#13]
I suck at creating buttons.

**Comment by rustyhodge** [comment]
What is the specs on the Icon? I'll get our designer to put something together.

**Comment by moneypenny** [comment]
What! Thank you! :) I think 48x48 and 128x128 PNGs are all I need. See https://github.com/moneypenny/soma-chrome/blob/master/extension/icon128.png and https://github.com/moneypenny/soma-chrome/blob/master/extension/icon48.png for what is currently in use.

**Comment by mikedillion** [comment]
:raised_hands: the man himself! :raised_hands:

**Comment by rustyhodge** [comment]
Here you go. New icon buttons.

**Comment by moneypenny** [comment]
Wait... I don't see any links/images @rustyhodge!

**Comment by rustyhodge** [comment]
Argh, the attachment didn't come through.

Here's a link to download them:

https://www.dropbox.com/sh/6j5jdd3sj1kgvgk/AABkJEXhQwoSvjm7t_cuhkv3a?dl=0

**Comment by moneypenny** [comment]
Thanks! They look good. I'll work them in tonight.

**Comment by moneypenny** [comment]
Version 0.0.0.6 with the new icon is live! https://chrome.google.com/webstore/detail/somaplayer/dpcghdgbhjkihgnnbojldhjmcbieofgo?hl=en&gl=US&authuser=1
