### ISSUE TITLE
Add ThistleRadio, SomaFM Live, and Earwaves stations

### ISSUE THREAD

**Issue by moneypenny** [moneypenny/soma-chrome#14]
Saw them listed on http://somafm.com/

**Comment by rustyhodge** [comment]
In a perfect world, this will parse http://api.somafm.com/channels.xml to get a list of the channels, their descriptions and their stream URLs.

<channels>
	<channel id="groovesalad">
		<title><![CDATA[Groove Salad]]></title>
		<description><![CDATA[A nicely chilled plate of ambient/downtempo beats and grooves.]]></description>
		<dj><![CDATA[Rusty Hodge]]></dj>
		<djmail><![CDATA[rusty@somafm.com]]></djmail>
		<genre>ambient|electronica</genre>
		<image>http://somafm.com/img/groovesalad120.png</image>
		<largeimage>http://somafm.com/logos/256/groovesalad256.png</largeimage>
		<xlimage>http://somafm.com/logos/512/groovesalad512.png</xlimage>
		<twitter>groovesalad</twitter>
		<updated>1433011049</updated>
		<fastpls format="mp3">http://somafm.com/groovesalad.pls</fastpls>
		<slowpls format="mp3">http://somafm.com/groovesalad56.pls</slowpls>
		<highestpls format="aac">http://somafm.com/groovesalad130.pls</highestpls>
		<fastpls format="aacp">http://somafm.com/groovesalad64.pls</fastpls>
		<slowpls format="aacp">http://somafm.com/groovesalad32.pls</slowpls>
		<listeners>2504</listeners>
		<lastPlaying><![CDATA[Tosca - Fuck Dub (Haaksman Mix)]]></lastPlaying>  
	</channel>
	<channel id="secretagent">
		<title><![CDATA[Secret Agent]]></title>
		<description><![CDATA[The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!]]></description>
		<dj><![CDATA[Rusty Hodge]]></dj>
		<djmail><![CDATA[rusty@somafm.com]]></djmail>
		<genre>lounge</genre>
		<image>http://somafm.com/img/secretagent120.jpg</image>
		<largeimage>http://somafm.com/logos/256/secretagent256.png</largeimage>
		<xlimage>http://somafm.com/logos/512/secretagent512.png</xlimage>
		<twitter>secretagentsoma</twitter>
		<updated>1433011049</updated>
		<fastpls format="mp3">http://somafm.com/secretagent.pls</fastpls>
		<slowpls format="mp3">http://somafm.com/secretagent24.pls</slowpls>
		<highestpls format="aac">http://somafm.com/secretagent130.pls</highestpls>
		<fastpls format="aacp">http://somafm.com/secretagent64.pls</fastpls>
		<slowpls format="aacp">http://somafm.com/secretagent32.pls</slowpls>
		<listeners>385</listeners>
		<lastPlaying><![CDATA[Solitaire (Elmar Schulte & Rudiger Gleisberg) - Tribes]]></lastPlaying>  
	</channel>
[...]
</channels>

**Comment by moneypenny** [comment]
Oh hey, that's perfect! Thanks. I've done some XML parsing in JavaScript before, shouldn't be bad.

**Comment by rustyhodge** [comment]
I have been meaning to add a JSON version of the channels.xml file, which if that would make it a lot easier, I'll try and get that together today.

**Comment by moneypenny** [comment]
It's not a big deal. With jQuery, you can just `$(myBlobOfXml)` and query different bits of it like you would the HTML DOM.

**Comment by moneypenny** [comment]
See also https://github.com/moneypenny/soma-chrome/issues/5

**Comment by moneypenny** [comment]
Fixed in https://github.com/moneypenny/soma-chrome/commit/7b7070f5b871ca75093376fa6561f9c6b886fdd1
